services:
  rebet_mirte:
    image: ghcr.io/kas-lab/mirte_playground:main
    container_name: mirte
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /dev/dri:/dev/dri
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    stdin_open: true       # equivalent to -it
    tty: true              # equivalent to -it
    restart: "no"          # equivalent to --rm (no restart)

